[platformio]
default_envs = node_a
src_dir = src

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_flags =
  --before=no_reset
  --after=hard_reset
  --no-stub
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DWIFI_SSID=\"FWA_ZG7P6R\"
  -DWIFI_PASSWORD=\"elm3-beam-fluke\"

[env:node_a]
build_flags =
  ${env.build_flags}
  -DNODE_ID=\"A\"
  -DNODE_LABEL=\"node_a\"
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0

[env:node_b]
build_flags =
  ${env.build_flags}
  -DNODE_ID=\"B\"
  -DNODE_LABEL=\"node_b\"
upload_port = /dev/ttyACM1
monitor_port = /dev/ttyACM1
